{{- if .Values.pdb.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "garuda-am-bridge.name" . }}
  labels:
    {{- include "garuda-am-bridge.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.pdb.minAvailable }}
  selector:
    matchLabels:
      {{- include "garuda-am-bridge.selectorLabels" . | nindent 6 }}
{{- end }}
